### ISSUE TITLE
Вопрос по работе

### ISSUE THREAD

**Issue by Toxenskiy** [shirosandev/VidIQSeoChecker#2]
Есть бот в телеграмме @CheckSEOBot, и у него совпадают значения с моим браузером, но с вашим кодом, какой бы я регион не ставил, совпадений нет

**Comment by shirosandev** [comment]
Привет. Мой скрипт не зависит от региона. Пробив идёт через сторонний сервис. Если хочешь, чтобы показатель SEO зависел от твоего региона, то нужно переписать получение позиций видео на запросы.
